using Eden_Relics_BE.DTOs;
using Eden_Relics_BE.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Eden_Relics_BE.Controllers;

/// <summary>
/// Admin-only endpoints for the regulatory-obligations calendar. Statutory rows are
/// auto-generated by <see cref="ILiabilityScheduleService"/>; the operator can also add
/// free-form events (Kind = Other). Scheduling an obligation creates a linked email reminder.
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize(Roles = "Admin")]
public class CalendarController(
    ICalendarService calendar,
    IOptions<LiabilityOptions> options) : ControllerBase
{
    private readonly LiabilityOptions _options = options.Value;

    /// <summary>Calendar config — whether the ARD is set and whether the iCal feed is enabled.</summary>
    [HttpGet("config")]
    public ActionResult<CalendarConfigDto> GetConfig()
    {
        bool ardConfigured = !string.IsNullOrWhiteSpace(_options.AccountingReferenceDate);
        bool icalEnabled = !string.IsNullOrWhiteSpace(_options.IcalToken);
        string? subscribeUrl = null;
        if (icalEnabled)
        {
            string scheme = Request.Scheme;
            string host = Request.Host.Value ?? "localhost";
            subscribeUrl = $"{scheme}://{host}/api/calendar/obligations.ics?token={Uri.EscapeDataString(_options.IcalToken!)}";
        }
        return Ok(new CalendarConfigDto(ardConfigured, icalEnabled, subscribeUrl));
    }

    /// <summary>List obligations within a date window (for the grid) or all open ones (for the sidebar).</summary>
    [HttpGet]
    public async Task<ActionResult<List<LiabilityObligationDto>>> GetAll(
        [FromQuery] DateOnly? from = null,
        [FromQuery] DateOnly? to = null,
        [FromQuery] bool openOnly = false,
        CancellationToken ct = default)
    {
        return Ok(await calendar.GetAllAsync(from, to, openOnly, ct));
    }

    /// <summary>Assign a work-session time to an obligation. Creates / updates the linked auto-reminder.</summary>
    [HttpPost("{id:guid}/schedule")]
    public async Task<ActionResult<LiabilityObligationDto>> Schedule(Guid id, ScheduleObligationRequest body, CancellationToken ct)
    {
        LiabilityObligationDto? row = await calendar.ScheduleAsync(id, body, ct);
        return row is null ? NotFound() : Ok(row);
    }

    /// <summary>Clear the assigned work-session time. Removes the linked auto-reminder.</summary>
    [HttpPost("{id:guid}/unschedule")]
    public async Task<ActionResult<LiabilityObligationDto>> Unschedule(Guid id, CancellationToken ct)
    {
        LiabilityObligationDto? row = await calendar.UnscheduleAsync(id, ct);
        return row is null ? NotFound() : Ok(row);
    }

    /// <summary>Mark an obligation done with evidence: submission reference, payment amount + reference, dates.</summary>
    [HttpPost("{id:guid}/complete")]
    public async Task<ActionResult<LiabilityObligationDto>> Complete(Guid id, CompleteObligationRequest body, CancellationToken ct)
    {
        LiabilityObligationDto? row = await calendar.CompleteAsync(id, body, ct);
        return row is null ? NotFound() : Ok(row);
    }

    /// <summary>Mark an obligation as N/A (waived).</summary>
    [HttpPost("{id:guid}/waive")]
    public async Task<ActionResult<LiabilityObligationDto>> Waive(Guid id, CancellationToken ct)
    {
        LiabilityObligationDto? row = await calendar.WaiveAsync(id, ct);
        return row is null ? NotFound() : Ok(row);
    }

    /// <summary>Undo a Complete / Waived. Drops back to Pending and re-creates the reminder if scheduled.</summary>
    [HttpPost("{id:guid}/reopen")]
    public async Task<ActionResult<LiabilityObligationDto>> Reopen(Guid id, CancellationToken ct)
    {
        LiabilityObligationDto? row = await calendar.ReopenAsync(id, ct);
        return row is null ? NotFound() : Ok(row);
    }

    /// <summary>Create a free-form calendar event (Kind = Other). The schedule generator never produces these.</summary>
    [HttpPost]
    public async Task<ActionResult<LiabilityObligationDto>> Create(CreateObligationRequest body, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(body.Title))
        {
            return BadRequest(new { error = "Title is required." });
        }
        return Ok(await calendar.CreateAsync(body, ct));
    }

    /// <summary>Delete a free-form event entirely. Statutory rows must be waived (the unique index would re-create them).</summary>
    [HttpDelete("{id:guid}")]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct)
    {
        DeleteObligationResult result = await calendar.DeleteAsync(id, ct);
        return result switch
        {
            DeleteObligationResult.NotFound => NotFound(),
            DeleteObligationResult.NotCustom => BadRequest(new { error = "Only custom events can be deleted. Use Mark N/A on statutory obligations instead." }),
            _ => NoContent(),
        };
    }
}
